
UPDATE PROJECT_CATALOG_FACT SET DURATION = DATEDIFF ( m , "START_DATE" , DEADLINE_DATE )  ;
UPDATE PROJECT_CATALOG_FACT SET DURATION_SPENT = DATEDIFF ( m , "START_DATE" , DEADLINE_DATE )     ;
UPDATE PROJECT_CATALOG_FACT SET PERCENTAGE_COMPLETE = Case when PERCENTAGE_COMPLETE is null then (DURATION_SPENT/DURATION) else (PERCENTAGE_COMPLETE) End ;

UPDATE PROJECT_CATALOG_FACT SET PR_START_IN_NEXT_6MON = Case when DATEDIFF ( m , "START_DATE" , CURRENT_TIMESTAMP ) between 0 and 6  and  DATEDIFF ( d , "START_DATE" , CURRENT_TIMESTAMP )>= 0 then 1 else 0 End ;
UPDATE PROJECT_CATALOG_FACT SET PR_END_IN_NEXT_6MON  = Case when (DATEDIFF ( m , CURRENT_TIMESTAMP ,DEADLINE_DATE) between 0 and 6) and   (DATEDIFF ( d , CURRENT_TIMESTAMP ,DEADLINE_DATE)>= 0) then 1 else 0 End ;
UPDATE PROJECT_CATALOG_FACT SET EST_BUDGET_SPENT = Case when EST_BUDGET_SPENT is null then EST_BUDGET* PERCENTAGE_COMPLETE else EST_BUDGET_SPENT End ;
UPDATE PROJECT_CATALOG_FACT SET PERCENTAGE_SPENT = Case when PERCENTAGE_SPENT is null then  PERCENTAGE_COMPLETE else PERCENTAGE_SPENT End;
UPDATE PROJECT_CATALOG_FACT SET PROJECT_STATUS_NUM = Case when UPPER(PROJECT_STATUS) = 'GREEN' then 3 when UPPER(PROJECT_STATUS) = 'YELLOW' then 2 when UPPER(PROJECT_STATUS) = 'RED' then 1 else 0 End;
UPDATE PROGRAM_DIMENSION SET PROGRAM_STATUS_NUM = Case when UPPER(PROGRAM_STATUS) = 'GREEN' then 3 when UPPER(PROGRAM_STATUS) = 'YELLOW' then 2 when UPPER(PROGRAM_STATUS) = 'RED' then 1 else 0 End;

UPDATE ISSUES_DIMENSION SET CRITICALITY_NUM = Case when UPPER(CRITICALITY) = 'GREEN' then 3 when UPPER(CRITICALITY) = 'YELLOW' then 2 when UPPER(CRITICALITY) = 'RED' then 1 else 0 End;
UPDATE ISSUES_DIMENSION SET IS_DUE_NXT_6MON = Case when (DATEDIFF ( m , CURRENT_TIMESTAMP ,RESOLUTION_DUE_DATE) between 0 and 6) and   (DATEDIFF ( d , CURRENT_TIMESTAMP ,RESOLUTION_DUE_DATE)>= 0) then 1 else 0 End ;

UPDATE ACTIVITY_DIMENSION SET ACTIVITY_DIMENSION.ACTIVITY_STATUS_NUM = Case when UPPER(ACTIVITY_STATUS_COLOR) = 'GREEN' then 3 when UPPER(ACTIVITY_STATUS_COLOR) = 'YELLOW' then 2 when UPPER(ACTIVITY_STATUS_COLOR) = 'RED' then 1 else 0 End;
UPDATE ACTIVITY_DIMENSION SET ACTIVITY_DIMENSION.ACT_START_IN_NEXT_6MON = Case when (DATEDIFF ( m , CURRENT_TIMESTAMP ,"START_DATE") between 0 and 6) and   (DATEDIFF ( d , CURRENT_TIMESTAMP ,"START_DATE")>= 0) then 1 else 0 End ;
UPDATE ACTIVITY_DIMENSION SET ACTIVITY_DIMENSION.ACT_END_IN_NEXT_6MON = Case when (DATEDIFF ( m , CURRENT_TIMESTAMP ,END_DATE) between 0 and 6) and   (DATEDIFF ( d , CURRENT_TIMESTAMP ,END_DATE)>= 0) then 1 else 0 End ;

UPDATE RISKS_DIMENSION SET CALCULATED_SEVERITY = PROBABILITY * IMPACT  ;

;
