CREATE TABLE `ACTIVITY` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `ACTIVITY_ID` double DEFAULT NULL,
   `ACTIVITY_NAME` varchar(100) DEFAULT NULL,
   `START_DATE` date DEFAULT NULL,
   `END_DATE` date DEFAULT NULL,
   `ACTIVITY_STATUS_COLOR` varchar(100) DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `ACTIVITY_DIMENSION` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `ACTIVITY_ID` double DEFAULT NULL,
   `ACTIVITY_NAME` varchar(100) DEFAULT NULL,
   `START_DATE` date DEFAULT NULL,
   `END_DATE` date DEFAULT NULL,
   `ACTIVITY_STATUS_NUM` int(11) DEFAULT NULL,
   `ACTIVITY_STATUS_COLOR` varchar(100) DEFAULT NULL,
   `ACT_START_IN_NEXT_6MON` int(1) DEFAULT NULL,
   `ACT_END_IN_NEXT_6MON` int(1) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `BATCHLOAD` (
   `BATCH_ID` int(11) NOT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`BATCH_ID`)
 ) ;
 
 CREATE TABLE `ERA` (
   `BAN` int(11) DEFAULT NULL,
   `CTN` int(11) DEFAULT NULL,
   `SUB_ACT_DATE` date DEFAULT NULL,
   `DATE_OF_CONSENT` date DEFAULT NULL,
   `ERA_CONSENT_STATUS` varchar(20) DEFAULT NULL,
   `Comments` varchar(100) DEFAULT NULL,
   `LOAD_DT` date DEFAULT NULL,
   `UPDATE_DT` date DEFAULT NULL,
   `EFF_START` date DEFAULT NULL,
   `EFF_END` date DEFAULT NULL
 ) ;
 
 CREATE TABLE `ISSUES` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `ISSUE_ID` varchar(100) DEFAULT NULL,
   `ISSUE_DESCRIPTION` varchar(500) DEFAULT NULL,
   `CRITICALITY` varchar(100) DEFAULT NULL,
   `RESOLUTION` varchar(500) DEFAULT NULL,
   `RESOLUTION_DUE_DATE` date DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `ISSUES_DIMENSION` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `ISSUE_ID` varchar(100) DEFAULT NULL,
   `ISSUE_DESCRIPTION` varchar(500) DEFAULT NULL,
   `CRITICALITY_NUM` int(11) DEFAULT NULL,
   `CRITICALITY` varchar(100) DEFAULT NULL,
   `RESOLUTION` varchar(500) DEFAULT NULL,
   `RESOLUTION_DUE_DATE` date DEFAULT NULL,
   `IS_DUE_NXT_6MON` int(1) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PORTFOLIO` (
   `PORTFOLIO_ID` varchar(100) DEFAULT NULL,
   `PORTFOLIO_DESCRIPTION` varchar(100) DEFAULT NULL,
   `PORTFOLIO_NOTES` varchar(100) DEFAULT NULL,
   `LEADERSHIP` varchar(100) DEFAULT NULL,
   `STATUS_SUMMARY` varchar(2000) DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `PORTFOLIO_DIMENSION` (
   `PORTFOLIO_ID` varchar(100) DEFAULT NULL,
   `PORTFOLIO_DESCRIPTION` varchar(100) DEFAULT NULL,
   `PORTFOLIO_NOTES` varchar(100) DEFAULT NULL,
   `LEADERSHIP` varchar(100) DEFAULT NULL,
   `STATUS_SUMMARY` varchar(2000) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROGRAM` (
   `PROGRAM_ID` varchar(10) DEFAULT NULL,
   `PROGRAM_NAME` varchar(50) DEFAULT NULL,
   `PROGRAM_NOTES` varchar(50) DEFAULT NULL,
   `PROGRAM_STATUS_SUMMARY` varchar(500) DEFAULT NULL,
   `INTAKE_EXECUTIVE_SUMMARY` varchar(200) DEFAULT NULL,
   `PROJECT_ADVANTAGE` varchar(50) DEFAULT NULL,
   `TITLE_ABBREVIATION` varchar(50) DEFAULT NULL,
   `PROJECT_TYPE` varchar(50) DEFAULT NULL,
   `PURPOSE_STATEMENT` varchar(200) DEFAULT NULL,
   `PROGRAM_SIZE` varchar(10) DEFAULT NULL,
   `PROGRAM_STATUS_NUM` int(1) DEFAULT NULL,
   `PROGRAM_STATUS` varchar(10) DEFAULT NULL,
   `DEPARTMENT` varchar(10) DEFAULT NULL,
   `DIVISION` varchar(100) DEFAULT NULL,
   `SPONSOR` varchar(50) DEFAULT NULL,
   `PMO` varchar(50) DEFAULT NULL,
   `PMO_DIRECTOR` varchar(50) DEFAULT NULL,
   `PRIMARY_VENDOR` varchar(50) DEFAULT NULL,
   `IV_AND_V_VENDOR` varchar(50) DEFAULT NULL,
   `FEDERAL_FUNDING_PARTNER` varchar(50) DEFAULT NULL,
   `SCHEDULE_1` varchar(100) DEFAULT NULL,
   `SCOPE` varchar(100) DEFAULT NULL,
   `FINANCE` varchar(100) DEFAULT NULL,
   `HUMAN_RESOURCES` varchar(100) DEFAULT NULL,
   `CONTRACT` varchar(100) DEFAULT NULL,
   `IV_AND_V` varchar(100) DEFAULT NULL,
   `SPONSOR_TITLE` varchar(50) DEFAULT NULL,
   `APD_NUMBER` varchar(100) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROGRAM_DIMENSION` (
   `PROGRAM_ID` varchar(10) DEFAULT NULL,
   `PROGRAM_NAME` varchar(50) DEFAULT NULL,
   `PROGRAM_NOTES` varchar(50) DEFAULT NULL,
   `PROGRAM_STATUS_SUMMARY` varchar(500) DEFAULT NULL,
   `INTAKE_EXECUTIVE_SUMMARY` varchar(200) DEFAULT NULL,
   `PROJECT_ADVANTAGE` varchar(50) DEFAULT NULL,
   `TITLE_ABBREVIATION` varchar(50) DEFAULT NULL,
   `PROJECT_TYPE` varchar(50) DEFAULT NULL,
   `PURPOSE_STATEMENT` varchar(200) DEFAULT NULL,
   `PROGRAM_SIZE` varchar(10) DEFAULT NULL,
   `PROGRAM_STATUS_NUM` int(1) DEFAULT NULL,
   `PROGRAM_STATUS` varchar(10) DEFAULT NULL,
   `DEPARTMENT` varchar(10) DEFAULT NULL,
   `DIVISION` varchar(100) DEFAULT NULL,
   `SPONSOR` varchar(50) DEFAULT NULL,
   `PMO` varchar(50) DEFAULT NULL,
   `PMO_DIRECTOR` varchar(50) DEFAULT NULL,
   `PRIMARY_VENDOR` varchar(50) DEFAULT NULL,
   `IV_AND_V_VENDOR` varchar(50) DEFAULT NULL,
   `FEDERAL_FUNDING_PARTNER` varchar(50) DEFAULT NULL,
   `SCHEDULE_1` varchar(100) DEFAULT NULL,
   `SCOPE` varchar(100) DEFAULT NULL,
   `FINANCE` varchar(100) DEFAULT NULL,
   `HUMAN_RESOURCES` varchar(100) DEFAULT NULL,
   `CONTRACT` varchar(100) DEFAULT NULL,
   `IV_AND_V` varchar(100) DEFAULT NULL,
   `SPONSOR_TITLE` varchar(50) DEFAULT NULL,
   `APD_NUMBER` varchar(100) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROJECT` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `PROJECT_NAME` varchar(100) DEFAULT NULL,
   `PROGRAM_ID` varchar(100) DEFAULT NULL,
   `PROGRAM_NAME` varchar(100) DEFAULT NULL,
   `PORTFOLIO_ID` varchar(100) DEFAULT NULL,
   `PORTFOLIO_NAME` varchar(100) DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROJECT_CATALOG` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `PROJECT_TITLE` varchar(100) DEFAULT NULL,
   `INTAKE_SUMMARY` varchar(100) DEFAULT NULL,
   `PROJECT_ADVANTAGE` varchar(100) DEFAULT NULL,
   `TITLE_ABBREVIATION` varchar(200) DEFAULT NULL,
   `PROJECT_TYPE` varchar(100) DEFAULT NULL,
   `PURPOSE_STATEMENT` varchar(1000) DEFAULT NULL,
   `PROJECT_SIZE` varchar(100) DEFAULT NULL,
   `PROJECT_STATUS_NUM` int(1) DEFAULT NULL,
   `PROJECT_STATUS` varchar(100) DEFAULT NULL,
   `DEPARTMENT` varchar(100) DEFAULT NULL,
   `DIVISION` varchar(100) DEFAULT NULL,
   `SPONSOR` varchar(100) DEFAULT NULL,
   `PMO` varchar(100) DEFAULT NULL,
   `PMO_DIRECTOR` varchar(100) DEFAULT NULL,
   `PROJECT_MANAGER` varchar(100) DEFAULT NULL,
   `PRIMARY_VENDOR` varchar(100) DEFAULT NULL,
   `IV_AND_V_VENDOR` varchar(100) DEFAULT NULL,
   `FEDERAL_FUNDING_PARTNER` varchar(100) DEFAULT NULL,
   `STAGE_GATE` varchar(100) DEFAULT NULL,
   `START_DATE` date DEFAULT NULL,
   `DEADLINE_DATE` date DEFAULT NULL,
   `AGENCY_PRIORITY` int(11) DEFAULT NULL,
   `DIVISION_PRIORITY` int(11) DEFAULT NULL,
   `DEPENDENCY_ON_PRIMARY_PROJECT` varchar(100) DEFAULT NULL,
   `FUND_TYPE` varchar(100) DEFAULT NULL,
   `FUND_SPLIT` varchar(100) DEFAULT NULL,
   `EST_BUDGET` varchar(100) DEFAULT NULL,
   `EST_BUDGET_SPENT` int(11) DEFAULT NULL,
   `EST_BUS_RSCS` int(11) DEFAULT NULL,
   `EST_TECH_RSCS` int(11) DEFAULT NULL,
   `EST_VEN_RSCS` int(11) DEFAULT NULL,
   `TOTAL_RSCS` int(11) DEFAULT NULL,
   `SUPPORT_STAGE_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `SUPPORT_AGENCY_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `SUPPORT_DIVISION_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `PRIMARY_BUSINESS_BENEFIT` varchar(100) DEFAULT NULL,
   `INVESTMENT_TRANSFORMATION_BENEFIT` varchar(100) DEFAULT NULL,
   `QUANTITATIVE_BENEFIT` varchar(100) DEFAULT NULL,
   `QUALITATIVE_BENEFIT` varchar(100) DEFAULT NULL,
   `BENEFIT_OWNER` varchar(100) DEFAULT NULL,
   `COMPLEXITY` double DEFAULT NULL,
   `BENEFIT` double DEFAULT NULL,
   `MANDATORY_OVERRIDE` varchar(100) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROJECT_CATALOG_FACT` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `PROJECT_TITLE` varchar(100) DEFAULT NULL,
   `INTAKE_SUMMARY` varchar(100) DEFAULT NULL,
   `PROJECT_ADVANTAGE` varchar(100) DEFAULT NULL,
   `TITLE_ABBREVIATION` varchar(200) DEFAULT NULL,
   `PROJECT_TYPE` varchar(100) DEFAULT NULL,
   `PURPOSE_STATEMENT` varchar(300) DEFAULT NULL,
   `PROJECT_SIZE` varchar(100) DEFAULT NULL,
   `PROJECT_STATUS_NUM` int(1) DEFAULT NULL,
   `PROJECT_STATUS` varchar(100) DEFAULT NULL,
   `DEPARTMENT` varchar(100) DEFAULT NULL,
   `DIVISION` varchar(100) DEFAULT NULL,
   `SPONSOR` varchar(100) DEFAULT NULL,
   `PMO` varchar(100) DEFAULT NULL,
   `PMO_DIRECTOR` varchar(100) DEFAULT NULL,
   `PROJECT_MANAGER` varchar(100) DEFAULT NULL,
   `PRIMARY_VENDOR` varchar(100) DEFAULT NULL,
   `IV_AND_V_VENDOR` varchar(100) DEFAULT NULL,
   `FEDERAL_FUNDING_PARTNER` varchar(100) DEFAULT NULL,
   `STAGE_GATE` varchar(100) DEFAULT NULL,
   `START_DATE` date DEFAULT NULL,
   `DEADLINE_DATE` date DEFAULT NULL,
   `AGENCY_PRIORITY` int(11) DEFAULT NULL,
   `DIVISION_PRIORITY` int(11) DEFAULT NULL,
   `DEPENDENCY_ON_PRIMARY_PROJECT` varchar(100) DEFAULT NULL,
   `FUND_TYPE` varchar(100) DEFAULT NULL,
   `FUND_SPLIT` varchar(100) DEFAULT NULL,
   `EST_BUDGET` varchar(100) DEFAULT NULL,
   `EST_BUDGET_SPENT` double DEFAULT NULL,
   `EST_BUS_RSCS` int(11) DEFAULT NULL,
   `EST_TECH_RSCS` int(11) DEFAULT NULL,
   `EST_VEN_RSCS` int(11) DEFAULT NULL,
   `TOTAL_RSCS` int(11) DEFAULT NULL,
   `SUPPORT_STAGE_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `SUPPORT_AGENCY_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `SUPPORT_DIVISION_STRATEGIC_GOAL` varchar(100) DEFAULT NULL,
   `PRIMARY_BUSINESS_BENEFIT` varchar(100) DEFAULT NULL,
   `INVESTMENT_TRANSFORMATION_BENEFIT` varchar(100) DEFAULT NULL,
   `QUANTITATIVE_BENEFIT` varchar(100) DEFAULT NULL,
   `QUALITATIVE_BENEFIT` varchar(100) DEFAULT NULL,
   `BENEFIT_OWNER` varchar(100) DEFAULT NULL,
   `COMPLEXITY` double DEFAULT NULL,
   `BENEFIT` double DEFAULT NULL,
   `MANDATORY_OVERRIDE` varchar(100) DEFAULT NULL,
   `SCHEDULE` varchar(20) DEFAULT NULL,
   `SCOPE` varchar(20) DEFAULT NULL,
   `FINANCE` varchar(20) DEFAULT NULL,
   `HUMAN_RESOURCES` varchar(20) DEFAULT NULL,
   `CONTRACT` varchar(20) DEFAULT NULL,
   `IV_AND_V` varchar(20) DEFAULT NULL,
   `SPONSOR_TITLE` varchar(100) DEFAULT NULL,
   `ID_OF_STAFF` double DEFAULT NULL,
   `FTE` double DEFAULT NULL,
   `PERCENTAGE_COMPLETE` double DEFAULT NULL,
   `PERCENTAGE_SPENT` double DEFAULT NULL,
   `APD_NUMBER` varchar(100) DEFAULT NULL,
   `DURATION` double DEFAULT NULL,
   `DURATION_SPENT` double DEFAULT NULL,
   `PERCENTAGE_TIME_SPENT` int(11) DEFAULT NULL,
   `PR_START_IN_NEXT_6MON` int(1) DEFAULT NULL,
   `PR_END_IN_NEXT_6MON` int(1) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `STATUS_SUMMARY` varchar(1500) DEFAULT NULL,
   `STATUS_GATE` varchar(100) DEFAULT NULL
 ) ;
 
 CREATE TABLE `PROJECT_DIMENSION` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `PROJECT_NAME` varchar(100) DEFAULT NULL,
   `PROGRAM_ID` varchar(100) DEFAULT NULL,
   `PROGRAM_NAME` varchar(100) DEFAULT NULL,
   `PORTFOLIO_ID` varchar(100) DEFAULT NULL,
   `PORTFOLIO_NAME` varchar(100) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `RISKS` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `RISK_ID` varchar(100) DEFAULT NULL,
   `RISK_EVENT` varchar(100) DEFAULT NULL,
   `RISK_CONSEQUENCE` varchar(100) DEFAULT NULL,
   `RESPONSE_PLAN` varchar(100) DEFAULT NULL,
   `PROBABILIY` double DEFAULT NULL,
   `SEVERITY_COLOR_INDICATOR` varchar(100) DEFAULT NULL,
   `IMPACT` double DEFAULT NULL,
   `CALCULATED_SEVERITY` varchar(100) DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `RISKS_DIMENSION` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `RISK_ID` varchar(100) DEFAULT NULL,
   `RISK_EVENT` varchar(100) DEFAULT NULL,
   `RISK_CONSEQUENCE` varchar(100) DEFAULT NULL,
   `RESPONSE_PLAN` varchar(100) DEFAULT NULL,
   `PROBABILITY` double DEFAULT NULL,
   `SEVERITY_COLOR_INDICATOR` varchar(100) DEFAULT NULL,
   `IMPACT` double DEFAULT NULL,
   `CALCULATED_SEVERITY` double DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `STAGELOAD` (
   `BATCH_ID` int(11) NOT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `TABLE_NAME` varchar(100) DEFAULT NULL,
   PRIMARY KEY (`BATCH_ID`)
 ) ;
 
 CREATE TABLE `STRATEGY` (
   `PROJECT_ID` varchar(10) DEFAULT NULL,
   `HEALTHCARE` decimal(11,2) DEFAULT NULL,
   `KNOWLEDGE_INNOVATION` decimal(11,2) DEFAULT NULL,
   `HEALTH_SAFETY_WELLBEING` decimal(11,2) DEFAULT NULL,
   `EFFICIENT_TRANSPERENCY_ACCOUNTABILITY` decimal(11,2) DEFAULT NULL,
   `RUN_BUSINESS` decimal(11,2) DEFAULT NULL,
   `GROW_BUSINESS` decimal(11,2) DEFAULT NULL,
   `TRANSFORM_BUSINESS` decimal(11,2) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `STRATEGY_DIMENSION` (
   `PROJECT_ID` varchar(10) DEFAULT NULL,
   `HEALTHCARE` decimal(11,2) DEFAULT NULL,
   `KNOWLEDGE_INNOVATION` decimal(11,2) DEFAULT NULL,
   `HEALTH_SAFETY_WELLBEING` decimal(11,2) DEFAULT NULL,
   `EFFICIENT_TRANSPERENCY_ACCOUNTABILITY` decimal(11,2) DEFAULT NULL,
   `RUN_BUSINESS` decimal(11,2) DEFAULT NULL,
   `GROW_BUSINESS` decimal(11,2) DEFAULT NULL,
   `TRANSFORM_BUSINESS` decimal(11,2) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
 CREATE TABLE `VENDOR` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `VENDOR` varchar(100) DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL
 ) ;
 
 CREATE TABLE `VENDOR_DIMENSION` (
   `PROJECT_ID` varchar(100) DEFAULT NULL,
   `VENDOR` varchar(100) DEFAULT NULL,
   `CREATED_DATE` timestamp NULL DEFAULT NULL,
   `UPDATED_DATE` timestamp NULL DEFAULT NULL,
   `BATCH_ID` int(11) DEFAULT NULL
 ) ;
 
